version: '3'

services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - '.docker/mysql/data:/var/lib/mysql'
    networks:
      - lorado

  redis:
    image: redis:alpine
    volumes:
      - '.docker/redis/data:/data'
    networks:
      - lorado

  nginx:
    depends_on:
      - php-fpm
    image: nginx:alpine
    volumes:
      - .:/var/www/laravel
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/log:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - lorado

  php-fpm:
    depends_on:
      - mysql
      - redis
    build:
      context: .docker/php-fpm
      dockerfile: Dockerfile
    image: lorado-php
    environment:
      XDEBUG_REMOTE_ENABLE: 0
    volumes:
      - .:/var/www/laravel
      - .docker/php-fpm/extra-config.ini:/usr/local/etc/php/conf.d/extra-config.ini
      - .docker/php-fpm/laravel-schedule:/etc/cron.d/laravel-schedule
    networks:
      - lorado

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - lorado

networks:
  lorado:
    driver: bridge
